servers:
  - id: filesystem
    name: File System Access
    command: npx
    args: 
      - "@modelcontextprotocol/server-filesystem"
      - "."
    description: Read and browse local files

  - id: time-server
    name: Time Server
    command: npx
    args:
      - "@modelcontextprotocol/server-time"
    description: Gets current time and timezone information

  - id: wikipedia
    name: Wikipedia Search
    command: npx
    args:
      - "@modelcontextprotocol/server-wikipedia"
    description: Search Wikipedia for educational content

  - id: weather
    name: Weather Data
    command: npx
    args:
      - "@modelcontextprotocol/server-weather"
    description: Get current weather information

    id: echo
    name: Echo Test Server
    command: npx
    args:
      - "@modelcontextprotocol/server-echo"
    description: Test MCP communication